# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: First workflow
on: [workflow_dispatch]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "First step"
        run: echo "hello world"
      - name: Goodbye
        run: echo "goodbye"
